travis:
  secure:
    BINSTAR_TOKEN: Z1l1DOcmbuzv6hqeTS0y2psU9D1AqS0fTCvLIDMw7z2ouADHZcOXsOYbuXzXPzNbmQBugrtNr3qi9x2MGhoDPPZ9u3r4zym/slrcUi3uFzXxwEecAH0OG9Zx4Ktz18Mku9+zjWeBG7fQ4K5UuKaP8eNO6LcREsYQLZIiVPg28UN+Efv1sur+NBbXLNx+kLpqQGMJ2NLYtvXWJHYwXuMWHLHt4I7PvIVGLkSyJ9dPS+6q46XOt1Fte/nG/IXPND7BRz3QKSk9S6H52wP2iva0U0RS+vMV/tWP6qPezg+GXvQQCWWf8o8cgBFRJuTFOqBC13I7zhH/j33HDL2azl5DvGmsyeNBwdaiC73prNnZukgGoSAy9GeNyhzX88fKa1DH/9KbLk05QAiCDVpZH3ZfdfWoz7WgWD5B7Jst/uetXSMIkyenXQmnsP7DHpmopVRWJJfVWSeTX1DCZOhk7WhUQL7qv3SjXd6KNhhsDvLSNstPgk/hc12rwV/yvpLXGip7g6mXekitEuoZfvv9eQuFGOsDveRka/QVEuG+vRIgGfmnYDUM4JQe3FVG3dKUwmEIZtbpwpuJptAUIfiO3kKDxQXOVqcrBwvU/W07jdp/JyfDOepJ0/ixGFnL4dbDymlsKnxbVc1KxnLerBQX5elmoOy5IS8+TTiWEEre3QSRHBI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
