travis:
  secure:
    BINSTAR_TOKEN: jjAOiZHNgANPNhxDCeyYdhw2aYcJQah/SGLzYERoyeIG8+NJFuQiwxu5E3pbGQc1NPkyD8Q27FVrsRmZdg8u6s6qrl8M5luhFRzX/iP/cQf9hHNfoskq7NbvZT7fHy7QRll/VcigzpD+TM3M93pzBWbO+/1sChCyz4/z1Stibo4pdBfdqlay4vPU33mj0r+uo1gldqDGXX6V3nOxk/9MJYebqPQ52MExPoviOiJF1yy/vX/J7aosmndI3I9FrW+KlMDWqzW1Sum8CWP5TijuGIbR5934lsM2QFWuxmAAWjl1Mo1Gky2zdW4qFg24noRgSrvRFYXmtILmGHk9TNq8xRViOxs3UL5bSYVTRfwE8oEuMu76XCUvi17/xy7pBGAkZ28YqsK1RijEdpwx3oHrlvUA9XhjfK+MsE0tvHxnhirxvc0VkmB9OBxp91z086M2m2j/PTyo1v/CWdUwIYqZwMd8/tiwshBh4wcRgZ7zTUGczRCuELTIrws4jsiDZrHUgmP/MlVjXzwg3mbbzGm+TPD39JTdjAbtWOPWX22LDjTwa4RP091GQ7jR+uX/hs/nVxIsPfyoLmLWXroNgjg52R6ZjZpc76ewtLhWulj9G2SxhLp9n9fQAAntRaw90h8cTOnQDYmfNsD/ndNY5STSD9ugAM5QVPAuF6oe6cv8fgA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
